# Sass
sass:
  style: compressed

# Site information
title: JDow.io
description: A Software Development and Information Security Blog
url: https://jdow.io
logo: /img/jdowio.png
timezone: America/New_York
repository: https://github.com/dow-j/jdow.io

# Posts
excerpt_separator: <!--more-->

# SEO
google_analytics_id: UA-109895875-2
webmaster_verifications:
  google: H-MdKpqki24_rLfdJpmA-mmp058rsddryeOo1mRyYng
  bing: 458150BA7AA467A6A35A693CE3117408

# Defaults
defaults:
  -
    scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "docs"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "blog_item"

# Collections
collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
  tutorials:
    output: true

# Social
social:
  twitter: 0xJDow
  github: Dow-J
  linkedin: joshua-dow-2187b6b5

twitter:
  username: 0xJDow

# Plugins
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .gitignore
  - CNAME
  - icomoon-selection.json
  - readme.md
