sass:
  style: compressed

google_analytics_id: UA-109895875-2
google_site_verification: H-MdKpqki24_rLfdJpmA-mmp058rsddryeOo1mRyYng

repository: https://github.com/dow-j/jdow.io

timezone: America/New_York

defaults:
  -
    scope:
      path: "_docs"
      type: "docs"
    values:
      layout: "docs"
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "blog_item"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
  tutorials:
    output: true

name: JDow.io
description: Software Engineering and Information Security Blog
url: http://jdow.io

twitter:
  username: J0shuaD0w

logo: /img/jdowio.png

plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji

exclude:
  - .gitignore
  - CNAME
  - icomoon-selection.json
  - readme.md
